# /*
#  * Filename: /home/deniojr/Desktop/ruby_on_rails_studies/library_api/config/database.yml
#  * Path: /home/deniojr/Desktop/ruby_on_rails_studies/library_api/config
#  * Created Date: Thursday, February 1st 2024, 4:02:58 pm
#  * Author: Dênio Barbosa Júnior
#  * 
#  * Copyright (c) 2024 Your Company
#  */


default: &default
  adapter: postgresql
  encoding: unicode
  database: library
  username: deniojr
  password: abcd
  host: localhost
  port: 5432
  sslmode: disable
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# development environment database
development:
  <<: *default
  database: books_development
  sslmode: disable

# test environment database
test:
  <<: *default
  database: books_test

# production environment database
production:
  <<: *default
  database: books_production
  username: books
  password: <%= ENV["BOOKS_DATABASE_PASSWORD"] %>
